<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Behaviors\" />
    <Folder Include="Handlers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AEspejo.FreightQuotes.CarrierApiClient\AEspejo.FreightQuotes.CarrierApiClient.csproj" />
    <ProjectReference Include="..\AEspejo.FreightQuotes.Domain\AEspejo.FreightQuotes.Domain.csproj" />
  </ItemGroup>

</Project>
