<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>822e066a-5afb-428c-a66c-7dedb211c372</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.8" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Scrutor" Version="6.1.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AEspejo.FreightQuotes.Infrastructure\AEspejo.FreightQuotes.Infrastructure.csproj" />
    <ProjectReference Include="..\AEspejo.FreightQuotes.Migrations.Sqlite\AEspejo.FreightQuotes.Migrations.Sqlite.csproj" />
    <ProjectReference Include="..\AEspejo.FreightQuotes.Migrations.SqlServer\AEspejo.FreightQuotes.Migrations.SqlServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Accessorials\Create\" />
    <Folder Include="Features\Carriers\Create\" />
    <Folder Include="Features\Constants\Create\" />
    <Folder Include="Features\Countries\Create\" />
    <Folder Include="Features\Quotes\Create\" />
    <Folder Include="Features\Quotes\Get\" />
    <Folder Include="Features\RateQuotes\Create\" />
    <Folder Include="Features\States\Create\" />
  </ItemGroup>

</Project>
